### ISSUE TITLE
Issue with genobj.bat

### ISSUE THREAD

**Issue by Henrydice** [ishaan95/blenderOpenDRIVEImporter#1]
Hi,

First off, many thanks for your work on this importer which seems to be exactly what I need !

However, when I try to run ./genobj.bat I received error messages regarding the path "build/Release/test-xodr" that cannot be found. The latter path "../../carla/Import" isn't found either. When I search on my computer these folders don't seem to exit indeed...

I'm not a programer so rather noob. I'm afraid I'm missing a crucial step in here...

**Comment by ishaan95** [comment]
Hi sorry for the late reply,

I've added a change to the README file which specifies running the `workflow.bat` script in the `libOpenDRIVE` directory that will install the "build/Release/test-xodr" executable file. Please reopen this issue if there are any other errors regarding this.
